# Generated by Django 3.2.4 on 2021-07-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='eposta',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='isim',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='yanit',
        ),
    ]
