# Generated by Django 3.2.4 on 2021-07-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210703_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='abc', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='isim',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
