# Generated by Django 3.2.4 on 2021-07-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210703_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='isim',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
