# Generated by Django 3.2.4 on 2021-07-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210703_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='isim',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
