# Generated by Django 3.2.4 on 2021-07-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210703_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='kimlik',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
